Update cl-ocdi.yaml

diff --git a/.github/workflows/cl-ocdi.yaml b/.github/workflows/cl-ocdi.yaml
--- a/.github/workflows/cl-ocdi.yaml
+++ b/.github/workflows/cl-ocdi.yaml
@@ -4,13 +4,12 @@ on:
   workflow_dispatch:
     inputs:
       VERSION:
-        description: 'Dockerイメージのバージョン (例: 1.0.0)'
-        required: true
-        default: '1.0.0'
+        description: 'Dockerイメージのバージョン (例: 1.0.3)'
+        required: true  # 必須入力
 
 env:
-  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
-  AWS_REGION: ${{ secrets.AWS_REGION }}
+  IMAGE_NAME: ghcr.io/wuyang026/cicd-study-service
+  AWS_REGION: ap-south-1
   ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
   MANIFEST_REPO: wuyang026/cicd-study-manifest   # manifestリポジトリ名
 
@@ -44,9 +43,14 @@ jobs:
       - name: Build JAR
         run: ./gradlew :app:api:bootJar
 
-      # 入力されたバージョンを環境変数に設定
+      # VERSION の設定（必須入力チェック）
       - name: Set VERSION
-        run: echo "VERSION=${{ github.event.inputs.VERSION }}" >> $GITHUB_ENV
+        run: |
+          if [ -z "${{ github.event.inputs.VERSION }}" ]; then
+            echo "ERROR: VERSION が入力されていません。必須です。"
+            exit 1
+          fi
+          echo "VERSION=${{ github.event.inputs.VERSION }}" >> $GITHUB_ENV
 
       # OIDC を使用して AWS CLI を設定
       - name: Configure AWS credentials via OIDC
@@ -105,6 +109,7 @@ jobs:
           git add $NEW_DEPLOYMENT_FILE
           git commit -m "Add new deployment for version ${{ env.VERSION }}"
           git push
+
 
 
 # name: CI-OIDC Build and Push with Auto Manifest Update
